### ISSUE TITLE
Browserslist: caniuse-lite is outdated

### ISSUE THREAD

**Issue by linking123** [blenderskool/blaze#112] opened 2021-04-23 01:36 UTC
when i run `docker-compose up -d`, get some err info.

   npm 7.10.0
   os is ubuntu 18.04

```
Step 16/20 : RUN npm run build
 ---> Running in 75649c6e8274

> blaze-frontend@2.1.1 build /app/client
> preact build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

 ssr-bundle.e1978.css ⏤  4.12 kB (+4.12 kB)
        ssr-bundle.js ⏤  30.6 kB (+30.6 kB)


   ssr-bundle.e1978.css ⏤  0 B (-4.12 kB)
          ssr-bundle.js ⏤  0 B (-30.6 kB)
       bundle.5f534.css ⏤  4.04 kB (+4.04 kB)
    bundle.*****.esm.js ⏤  33.8 kB (+33.8 kB)
 polyfills.*****.esm.js ⏤  2.02 kB (+2.02 kB)
                  sw.js ⏤  10.6 kB (+10.6 kB)
              sw-esm.js ⏤  10.6 kB (+10.6 kB)
        bundle.fc54b.js ⏤  34.5 kB (+34.5 kB)
     polyfills.694cb.js ⏤  2.01 kB (+2.01 kB)


ReferenceError: window is not defined
method: os/r
at: /app/client/src/utils/urls.js:5:8

Source code:

export default {
  WS_HOST: (() => {
    if (WS_HOST) return WS_HOST;
    if (window.location.protocol === 'https:') {
      return `wss://${window.location.host}/ws`;
    } else {
      return `ws://${window.location.host}/ws`;
    }

This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blaze-frontend@2.1.1 build: `preact build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blaze-frontend@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-23T01_16_06_119Z-debug.log
```

**Comment by blenderskool** [comment] 2021-04-23 05:04
Closing this as it's a duplicate of #108

**Closed by blenderskool** 2021-04-23 05:04 UTC
